#!/usr/bin/env bash
# Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
count=0
while [ $count -ge 0 ]
do
	echo "To infinity and beyond"
	if pkill -15 7-highlander
	then
		echo "I am invincible!!!"
	fi
	sleep 2
done
