#!/usr/bin/env bash
# Displays numbers from 1 to 20 in between add the following:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

coun=1

while [ $coun -le 20 ]
do
  echo "$coun"
  case $coun in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( coun++ ))
done
